server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_route # payment_route # 路由的ID 没有固定规则但是要求唯一，建议配置服务名
#          uri: http://localhost:8001 # 匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE # 匹配后提供服务的路由地址 动态地址
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由
        - id: payment_route2 # payment_route # 路由的ID 没有固定规则但是要求唯一，建议配置服务名
          # uri: http://localhost:8001 # 匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE # 匹配后提供服务的路由地址 动态地址
          predicates:
            - Path=/payment/lb/** # 断言，路径相匹配的进行路由
            # - After=2022-07-23T10:52:17.381+08:00[Asia/Shanghai]
            # - Cookie=username,luxiaogen
            # - Header=X-Request-Id, \d+ # 请求头要有X-Request-Id属性并且值为整数的正则表达式
            # - Method=GET # 必须为GET请求
            #- Query=pass, \d+ # 要有参数pass并且值为整数才能访问
          #filters:
            #- AddRequestHeader=X-Request-red, blue

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
