server:
  port: 80

eureka:
  client:
    register-with-eureka: false # 注册为eureka的客户端
    service-url:
      # 设置Eureka Server 交互的地址服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

# 设置 feign 客户端超时时间(openfeign默认支持ribbon)
ribbon:
  # 指定是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  # 指的是建立连接后从费为其读取到可用资源所用的事件
  ConnectTimeout: 5000

logging:
  level:
    # feign 日志以什么级别监控哪个接口
    com.atguigu.springcloud.feignclient.PaymentFeignClient: debug